public enum AllianceFunBtnType
{
	A_NAME_MODIFY,
	A_FLAG_MODIFY,
	A_ALLIANCE_SEARCH,
	A_ALLIANCE_VIEW,
	A_ALLIANCE_PAI_HANG,
	A_ALLIANCE_COMMENT,
	A_ALLIANCE_BLOCK,
	A_ALLIANCE_COMBINE,
	A_QUIT,
	A_DISMISS
}
