public enum BattleMailType
{
	BATTLE_DEFAULT = 0,
	BATTLE_PLAYER_CITY = 1,
	BATTLE_RESOURCE = 2,
	BATTLE_CAMP = 3,
	BATTLE_TERRITORY_MAIN = 4,
	BATTLE_TERRITORY_TOWER = 5,
	BATTLE_KING = 6,
	BATTLE_BUILDING_NPC = 7,
	BATTLE_ATT_CITY_INVADE = 9,
	BATTLE_WHEEL_FIGHT = 10,
	BATTLE_BF_KING = 11
}
