public enum HeroSkillType
{
	DEFAULT = 0,
	GLOBAL_SKILL = 1,
	FORMATION_SKILL = 2,
	ROBOT_SKILL = 3,
	NORMAL_SKILL = 10,
	RAGE_SKILL = 11,
	START_BATTLE_SKILL = 12,
	SPECIAL_HERO_ADD_SKILL = 13,
	SUB_SKILL = 14
}
