public enum InvitePanelType
{
	INVITE = 0,
	OFFICIAL = 1,
	UN_KINGDOM_OFFICIAL = 2,
	KINGSGIFT = 3,
	UN_KINGDOM_KINGSGIFT = 4,
	ITEM_GIFT = 5,
	ITEM_DONATE = 6,
	ARMORY_GIFT = 21,
	PRISON_GIFT = 22,
	LABORATORY_GIFT = 23,
	SUPER_MARKET_GIFT = 24,
	SEND_SCORE = 25,
	SEND_GIFT = 26,
	ARENA_INVITE = 27,
	UN_KINGDOM_Medal = 28,
	CROSS_OFFICIAL = 29
}
