public enum OfficerRecruitType
{
	RECRUIT_TYPE_COMMON = 1,
	RECRUIT_TYPE_SENIOT,
	RECRUIT_TYPE_ACTIVITY,
	RECRUIT_TYPE_FREE,
	RECRUIT_TYPE_SPECIAL,
	RECRUIT_TYPE_HERO_ACTIVITY,
	RECRUIT_TYPE_HERO_OPTIONAL_ALL,
	RECRUIT_TYPE_HERO_OPTIONAL_OWN
}
