public enum PushType
{
	PUSH_GM = 0,
	PUSH_QUEUE = 1,
	PUSH_WORLD = 2,
	PUSH_MAIL = 3,
	PUSH_STATUS = 4,
	PUSH_ALLIANCE = 5,
	PUSH_ACTIVITY = 6,
	PUSH_RESOURCE = 7,
	PUSH_CHAT = 8,
	PUSH_REWARD = 9,
	PUSH_WEB_ONLINE = 10,
	PUSH_ATTACK = 11,
	PUSH_SCOUT = 12,
	NOT_CHECK = 99
}
