public enum WorldActivityType
{
	FIGHT_OF_KING = 0,
	FIGHT_OF_ARMORY = 7,
	FIGHT_OF_PRISON = 8,
	FIGHT_OF_LABORATORY = 9,
	FIGHT_OF_SUPERMARKET = 10,
	FIGHT_OF_GREATKING = 11,
	FIGHT_OF_DESERT_THRONE = 12
}
