<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Mono.Security">
      <HintPath>../../../re/dlls/Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../re/dlls/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics">
      <HintPath>../../../re/dlls/System.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../re/dlls/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>