<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DOTweenPro</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>../../../re/dlls/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>../../../re/dlls/DOTween.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>