<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FibMatrix.Rendering</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../../re/dlls/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>../../../re/dlls/Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="DOTweenPro">
      <HintPath>../../../re/dlls/DOTweenPro.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>../../../re/dlls/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>../../../re/dlls/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>../../../re/dlls/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="FibMatrix.BaseUtils">
      <HintPath>../../../re/dlls/FibMatrix.BaseUtils.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>../../../re/dlls/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>../../../re/dlls/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>../../../re/dlls/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>