<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sirenix.OdinInspector.Attributes</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../../re/dlls/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>../../../re/dlls/UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>