<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XAssetProRuntime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../../re/dlls/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>../../../re/dlls/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>../../../re/dlls/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>../../../re/dlls/System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="BaseUtils">
      <HintPath>../../../re/dlls/BaseUtils.dll</HintPath>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>../../../re/dlls/System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>../../../re/dlls/ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>../../../re/dlls/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>../../../re/dlls/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>