<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>netstandard</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../../re/dlls/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>../../../re/dlls/System.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <HintPath>../../../re/dlls/System.Data.DataSetExtensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing.Common">
      <HintPath>../../../re/dlls/System.Drawing.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>../../../re/dlls/System.IO.Compression.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression.FileSystem">
      <HintPath>../../../re/dlls/System.IO.Compression.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition">
      <HintPath>../../../re/dlls/System.ComponentModel.Composition.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>../../../re/dlls/System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics">
      <HintPath>../../../re/dlls/System.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <HintPath>../../../re/dlls/System.Runtime.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="System.Transactions">
      <HintPath>../../../re/dlls/System.Transactions.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services">
      <HintPath>../../../re/dlls/System.Web.Services.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../re/dlls/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <HintPath>../../../re/dlls/System.Xml.Linq.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>